# Copyright 2025 snowy-jaguar
# Contact: @snowyjaguar (Discord)
# Contact: contact@snowyjaguar.xyz (Email)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

version: '2'
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - asasalint
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - errchkjson
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gosec
    - ireturn
    - lll
    - maintidx
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - recvcheck
    - tagliatelle
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - emptyFallthrough
        - hugeParam
        - rangeValCopy
        - unnamedResult
        - whyNoLint
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - allowedPackages: ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"]
        - name: empty-block
          disabled: true
        - name: exported
          disabled: true
        - name: filename-format
          arguments:
            - ^[a-z][-0-9_a-z]*(?:\.gen)?\.go$
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
    staticcheck:
      checks:
       - 'all'
       - '-ST1000'
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
      - linters:
          - forbidigo
        path: ^internal/cmds/
      - linters:
          - forcetypeassert
        path: _test\.go$
      - linters:
          - forbidigo
        path: assets/scripts/generate-commit.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/snowy-jaguar/adguardhomesync-swarm)
    gofumpt:
      module-path: github.com/snowy-jaguar/adguardhomesync-swarm
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/snowy-jaguar/adguardhomesync-swarm
    golines:
      max-len: 128
      tab-len: 4
